### PR TITLE
Allow sync function to continue syncing repositories despite migration errors

### PR DESCRIPTION
**Pull request by AndreIglesias**
## Description:

This pull request addresses a limitation in the `sync` function, enabling it to proceed with syncing repositories even if migration errors occur. Previously, encountering a migration error halted the process, preventing the synchronization of remaining repositories. This modification ensures that all eligible repositories are synced, even if conflicts arise during migration.

## Changes Made:

1. Implemented error handling using a try-except block to catch `GiteaMigrationError` exceptions during repository migration.
2. Updated the logic to continue syncing repositories even if migration errors occur, allowing the process to proceed uninterrupted.
3. Enhanced reporting to provide detailed information about failed migrations while still migrating the remaining repositories.

### Before:
```python
gt.migrate_repo(repo=repo, github_token=conf.github_token)
```

### After:
```python
try:
    gt.migrate_repo(repo=repo, github_token=conf.github_token)
except gitea.GiteaMigrationError as e:
    print(f"[red]Migration Error for [b]{e.full_repo_name}[/]")
    len_repos -= 1
```

### Outcome:

With these modifications, the sync function now ensures that all eligible repositories are synced, regardless of migration errors encountered along the way. This enhancement provides users with a more resilient synchronization process, allowing them to address migration conflicts for individual repositories while continuing to migrate the remaining repositories seamlessly.

### CODE REVIEW

**Comment by qaniere** [comment]
Theses change work well on my machine, fixed my issue, thanks !

**Comment by Muscaw** [comment]
Hey, thank you very much for your PR. 

I'm sorry I did not see it earlier. This looks good to me. Though, I kind of stopped using it as Gitea does not allow to programmatically update the mirroring token.

Instead, I created https://github.com/Muscaw/GitFortress. I plan to add mirroring to Gitea if that's something you have an interest in.

**Comment by Muscaw** [comment]
@AndreIglesias I let the tests execute and some are now failing. Would you be interested in contributing to the tests as well? Otherwise I can do it if you don't have time.

You can easily verify the linting and tests are passing with the command `poetry run tox -elint`

**Comment by AndreIglesias** [comment]
Hey @Muscaw, thanks for letting me know! :)

I've added the necessary coverage tests for the **`GiteaMigrationError`** on the `sync()` and the `migrate_repo()` commands in `cli.py`, and they are passing now.
```
---------- coverage: platform linux, python 3.11.2-final-0 -----------
Name                              Stmts   Miss  Cover   Missing
---------------------------------------------------------------
gitea_github_sync/__init__.py         0      0   100%
gitea_github_sync/__main__.py         2      2     0%   1-3
gitea_github_sync/cli.py             70      0   100%  <======
gitea_github_sync/config.py          12      0   100%
gitea_github_sync/gitea.py           42      0   100%
gitea_github_sync/github.py          12      0   100%
gitea_github_sync/migration.py        5      0   100%
gitea_github_sync/repository.py      22      0   100%
---------------------------------------------------------------
TOTAL                               165      2    99%
Coverage XML written to file ./coverage.xml
```

**Pull request merged**
